from enum import Enum
from functools import partial
from typing import List, Literal, Callable, TypedDict, Awaitable, Union, get_args, cast, Any

from opentelemetry import trace
from pydantic import BaseModel, Field
import weaviate.classes as wvc

tracer = trace.get_tracer("grimoire.entity.tools")
ToolName = Literal["private_search", "web_search"]
AsyncCallable = Callable[..., Awaitable]


class Condition(BaseModel):
    namespace_id: str
    user_id: str | None = Field(default=None)
    record_type: str | None = Field(default=None)
    resource_ids: list[str] | None = Field(default=None)
    parent_ids: list[str] | None = Field(default=None)
    created_at: tuple[float, float] | None = Field(default=None)
    updated_at: tuple[float, float] | None = Field(default=None)

    def to_weaviate_filters(self) -> Any:
        where = wvc.query.Filter.by_property("namespace_id").equal(self.namespace_id)

        if self.user_id:
            where = where & (
                wvc.query.Filter.by_property("user_id").is_none(True)
                | wvc.query.Filter.by_property("user_id").equal(self.user_id)
            )

        if self.record_type:
            where = where & wvc.query.Filter.by_property("type").equal(self.record_type)

        if self.resource_ids:
            resource_filter = None
            for rid in self.resource_ids:
                each = wvc.query.Filter.by_property("chunk.resource_id").equal(rid)
                resource_filter = each if resource_filter is None else (resource_filter | each)
            if resource_filter is not None:
                where = where & resource_filter

        if self.parent_ids:
            parent_filter = None
            for pid in self.parent_ids:
                each = wvc.query.Filter.by_property("chunk.parent_id").equal(pid)
                parent_filter = each if parent_filter is None else (parent_filter | each)
            if parent_filter is not None:
                where = where & parent_filter

        if self.created_at is not None:
            where = where & wvc.query.Filter.by_property("chunk.created_at").greater_or_equal(
                self.created_at[0]
            )
            where = where & wvc.query.Filter.by_property("chunk.created_at").less_or_equal(
                self.created_at[1]
            )

        if self.updated_at is not None:
            where = where & wvc.query.Filter.by_property("chunk.updated_at").greater_or_equal(
                self.updated_at[0]
            )
            where = where & wvc.query.Filter.by_property("chunk.updated_at").less_or_equal(
                self.updated_at[1]
            )

        return where


class ToolExecutorConfig(TypedDict):
    name: str
    schema: dict
    func: AsyncCallable


class BaseTool(BaseModel):
    name: ToolName

    def to_func(self, func: AsyncCallable, **kwargs) -> AsyncCallable:
        return partial(func, **kwargs) if kwargs else func


class PrivateSearchResourceType(str, Enum):
    RESOURCE = "resource"
    FOLDER = "folder"


class Resource(BaseModel):
    id: str
    name: str
    type: PrivateSearchResourceType
    child_ids: list[str] | None = Field(default=None, exclude=True)


class PrivateSearchTool(BaseTool):
    name: Literal["private_search"] = "private_search"
    namespace_id: str
    visible_resources: list[Resource] = Field(
        default=None,
        exclude=True,
        description="Required in `AgentRequest`, excluded in `MessageDto`.",
    )
    resources: list[Resource] = Field(default=None)
    related_resources: list[Resource] = Field(
        default=None,
        description="Related resources of user's query, this field exists only when field resources is None. "
        "Generated by `UserQueryPreprocessor`.",
    )

    @tracer.start_as_current_span("PrivateSearchTool.to_condition")
    def to_condition(self) -> Condition:
        if self.visible_resources is None:
            raise AssertionError(
                "`visible_resources` must be provided when export to `Condition`."
            )
        trace.get_current_span().set_attribute(
            "len(visible_resources)", len(self.visible_resources)
        )
        return Condition(
            namespace_id=self.namespace_id,
            resource_ids=[r.id for r in self.visible_resources],
        )

    def to_func(self, func: AsyncCallable, /, **kwargs) -> AsyncCallable:
        return super().to_func(func, **(kwargs | {"condition": self.to_condition()}))


class WebSearchTool(BaseTool):
    name: Literal["web_search"] = "web_search"


_Tool = Union[PrivateSearchTool, WebSearchTool]
ALL_TOOLS: tuple[str] = cast(tuple[str], get_args(ToolName))


class ToolDict:
    def __init__(self, tools: list[_Tool]) -> None:
        self.tools: list[_Tool] = tools

    @property
    def dict(self) -> dict[str, _Tool]:
        return {tool.name: tool for tool in self.tools}

    def __getitem__(self, item: str) -> dict:
        return self.dict[item]

    def __contains__(self, item: str) -> bool:
        return item in self.dict

    def get(self, item: str, default=None) -> _Tool | None:
        return self.dict.get(item, default)
